[versions]
agp = "8.4.0"
sshd = "2.17.1"
eddsa = "0.3.0"
ktor = "3.2.3"

[libraries]
apache-sshd-core = { group = "org.apache.sshd", name = "sshd-core", version.ref = "sshd" }
eddsa = { group = "net.i2p.crypto", name = "eddsa", version.ref = "eddsa" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktor-client-websockets = { group = "io.ktor", name = "ktor-client-websockets", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
